### PR TITLE
Restrict offensive roasts to NSFW channels

### PR DESCRIPTION
**Pull request by AceAttorneyMaster111**
This commit checks the NSFW status of the command's channel. If it is not NSFW, the random roast generator picks from a pre-selected list of safe commands.

However, since I do not have access to the /data folder, a repo admin will have to manually change `/data/roast.json` to this format:

```json
{
  "safe": ["all", "the", "safe", "roasts", "here"],
  "nsfw": ["offensive", "roasts", "go", "here"]
}
```

My suggestion for choosing which roasts go where is if it contains profanity, death/suicide, or mental health comments, but that is up to the maintainer of the bot.

### CODE REVIEW

**Comment by gavwin** [comment]
No need to merge to keep up with master, I can do that manually when I'm ready to merge this PR.

**Comment by AceAttorneyMaster111** [comment]
Oh sorry. I just wanted to pull the code onto my fork so my other development branches are updated. Is there a better way to do that? (yeah… 6/7 commits are just merge and merge-related commits…)

**Comment by gavwin** [comment]
If you're doing that, then nvm what I said you can do it here.

**Comment by gavwin** [comment]
Not going to end up getting merged.

**Pull request closed without merging**
